version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./certs:/mosquitto/certs:ro
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
  publisher:
    image: eclipse-mosquitto:2
    entrypoint: ["sh","-c","apk add --no-cache mosquitto-clients && while true; do sleep 3600; done"]
  subscriber:
    image: eclipse-mosquitto:2
    entrypoint: ["sh","-c","apk add --no-cache mosquitto-clients && while true; do sleep 3600; done"]
# Generate certs and create mosquitto.conf with TLS settings before starting.
